### ISSUE TITLE
HTMLElement.shadowRoot is deprecated.

### ISSUE THREAD

**Issue by ygcaicn** [mark-hahn/markdown-scroll-sync#219] opened 2017-10-24 07:22 UTC
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `shadowRoot` and access
the editor contents directly instead.
```
HTMLElement.shadowRoot (/snap/atom/36/usr/share/atom/resources/app/src/text-editor-element.js:13:10)
MarkdownScrlSync.getVisTopHgtBot (/home/jachin/.atom/packages/markdown-scroll-sync/lib/utils.coffee:20:33)
MarkdownScrlSync.setMap (/home/jachin/.atom/packages/markdown-scroll-sync/lib/map.coffee:25:14)
MarkdownScrlSync.startTracking (/home/jachin/.atom/packages/markdown-scroll-sync/lib/main.coffee:75:12)
<unknown> (/home/jachin/.atom/packages/markdown-scroll-sync/lib/main.coffee:58:23)
Workspace.observeActivePaneItem (<embedded>:27222:13)
```

**Comment by lucasvieites** [comment] 2017-10-24 13:50
duplicate of #94

**Closed as completed** 2020-12-24 01:43 UTC
