### ISSUE TITLE
HTMLElement.shadowRoot is deprecated.

### ISSUE THREAD

**Issue by shantanoo-desai** [mark-hahn/markdown-scroll-sync#157] opened 2017-08-22 09:34 UTC
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `shadowRoot` and access
the editor contents directly instead.
```
HTMLElement.shadowRoot (C:\Users\des\AppData\Local\atom\app-1.19.2\resources\app\src\text-editor-element.js:13:10)
MarkdownScrlSync.getVisTopHgtBot (C:\Users\des\.atom\packages\markdown-scroll-sync\lib\utils.coffee:20:33)
MarkdownScrlSync.setMap (C:\Users\des\.atom\packages\markdown-scroll-sync\lib\map.coffee:25:14)
MarkdownScrlSync.startTracking (C:\Users\des\.atom\packages\markdown-scroll-sync\lib\main.coffee:75:12)
<unknown> (C:\Users\des\.atom\packages\markdown-scroll-sync\lib\main.coffee:58:23)
Function.module.exports.Emitter.simpleDispatch (<embedded>:63374:20)
```

On Windows 10 with `markdown-scroll-sync 2.1.2` 

package installed:
     `markdown-format-2.5.1` and `markdown-writer 2.6.5`

**Comment by lucasvieites** [comment] 2017-10-24 13:44
duplicate of #94

**Closed as completed** 2018-06-25 08:08 UTC
