### ISSUE TITLE
markdown-scroll-sync auto-hides tab-bar?

### ISSUE THREAD

**Issue by knobhead** [mark-hahn/markdown-scroll-sync#24] opened 2015-07-02 15:59 UTC
Hi,

this nifty plug-in unfortunately seems to be responsible for the tab-bar being automatically hidden whenever a markdown-preview tab is opened. Have to press `ctrl-alt-p` once to show it again.

**Atom 1.0 on Win7**
### Installed Packages

```coffee
# User
altgr, v0.1.0
autocomplete-php, v0.3.6
color-picker, v2.0.7
compare-files, v0.6.1
copy-config-info, v0.4.0
docblockr, v0.7.2
emmet-simplified, v2.4.2
file-icons, v1.5.8
indentation-indicator, v0.6.0
language-batch, v0.3.3
linter, v1.1.0
linter-php, v0.0.15
markdown-scroll-sync, v0.4.0
minimap-bookmarks, v0.1.0
minimap-linter, v1.0.0
minimap-selection, v4.3.0
monokai-syntax-for-one-dark, v0.2.2
open-recent, v2.2.4
useful-context-menu, v0.2.1

No Errors are thrown or displayed in the console. Any help is appreciated. If you need more debug information, let me know what exactly you need and how to get it (i'm new to atom).

If this is intended (but not documented...) behaviour, please let me know :)

Thanks!

**Comment by mark-hahn** [comment] 2015-07-02 17:10
Duplicate of #21.

**Closed by mark-hahn** 2015-07-02 17:10 UTC
