### ISSUE TITLE
HTMLElement.shadowRoot is deprecated.

### ISSUE THREAD

**Issue by ghost** [mark-hahn/markdown-scroll-sync#145] opened 2017-08-11 02:40 UTC
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `shadowRoot` and access
the editor contents directly instead.
```
HTMLElement.shadowRoot (C:\Users\lean\AppData\Local\atom\app-1.19.0-beta7\resources\app\src\text-editor-element.js:13:10)
MarkdownScrlSync.getVisTopHgtBot (C:\Users\lean\.atom\packages\markdown-scroll-sync\lib\utils.coffee:20:33)
MarkdownScrlSync.setMap (C:\Users\lean\.atom\packages\markdown-scroll-sync\lib\map.coffee:25:14)
MarkdownScrlSync.startTracking (C:\Users\lean\.atom\packages\markdown-scroll-sync\lib\main.coffee:75:12)
<unknown> (C:\Users\lean\.atom\packages\markdown-scroll-sync\lib\main.coffee:58:23)
Function.module.exports.Emitter.simpleDispatch (<embedded>:63277:20)
```

**Comment by lucasvieites** [comment] 2017-10-24 13:42
duplicate of #94

**Closed as completed** 2020-03-18 12:18 UTC
