### ISSUE TITLE
HTMLElement.shadowRoot is deprecated.

### ISSUE THREAD

**Issue by gkze** [mark-hahn/markdown-scroll-sync#143] opened 2017-08-08 19:00 UTC
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `shadowRoot` and access
the editor contents directly instead.
```
HTMLElement.shadowRoot (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:13:10)
MarkdownScrlSync.getVisTopHgtBot (/Users/george/.atom/packages/markdown-scroll-sync/lib/utils.coffee:20:33)
MarkdownScrlSync.setMap (/Users/george/.atom/packages/markdown-scroll-sync/lib/map.coffee:25:14)
MarkdownScrlSync.startTracking (/Users/george/.atom/packages/markdown-scroll-sync/lib/main.coffee:75:12)
<unknown> (/Users/george/.atom/packages/markdown-scroll-sync/lib/main.coffee:58:23)
Function.module.exports.Emitter.simpleDispatch (<embedded>:63277:20)
```

**Comment by lucasvieites** [comment] 2017-10-24 13:42
duplicate of #94

**Closed as completed** 2021-12-07 06:29 UTC
